import sys

def error(file_path, message):
    print(f"Error in {file_path}: {message}")
    sys.exit(1)
